AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Role: arn:aws:iam::582450002492:role/LabRole
      StageName: production
  ApiFunction: # Adds a GET method at the root resource via an Api event
    Role: arn:aws:iam::582450002492:role/LabRole
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - arn:aws:lambda:us-east-1:582450002492:layer:techno-layer:1
      Events:
        ListAllOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        CreateOrders:
          Type: Api
          Properties:
            Path: /orders
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        GetOrder:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        DeleteOrder:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: put
            RestApiId:
              Ref: ApiGatewayApi
        GetStepFunction:
          Type: Api
          Properties:
            Path: /status/{executionArn}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        ListAllCustomers:
          Type: Api
          Properties:
            Path: /customers
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        GetOrderEvent:
          Type: Api
          Properties:
            Path: /products
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      FunctionName: techno-lambda-order-management
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          SECRET_ARN: arn:aws:secretsmanager:us-east-1:582450002492:secret:techno-secret-rds-credentials-AMDrYs
          STEP_FUNCTIONS_ARN: changeme
      VpcConfig:
        SecurityGroupIds:
          - sg-07358962d18c8bf54
        SubnetIds:
          - subnet-0a2ba53ad21fc61e1
          - subnet-010210e102f6de793
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}