Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: techno-secret-rds-credentials
      Description: This secret has a hardcoded password in SecretString (use GenerateSecretString instead)
      SecretString: '{"username":"dbadmin", "host": "techno-rds-mydbcluster-l0firmc68ecd.crtggm5bj0qs.us-east-1.rds.amazonaws.com", "password": "TechnoCloud2026!", "dbname": "ordersdb"}'
      Tags:
        -
          Key: Name
          Value: techno-secret-rds-credentials
  
  # MySecretRotationSchedule:
  #   Type: AWS::SecretsManager::RotationSchedule
  #   Properties:
  #     SecretId: !Ref MySecret
  #     RotationRules:
  #       ScheduleExpression: 'rate(30 days)'