Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "handi@seamolec.org"
          Protocol: "email"
      TopicName: "lks-sns-order-notifications"

Outputs:
  TopicArn:
    Description: The ARN of the created SNS topic
    Value: !Ref SNSTopic
         